### PR TITLE
Add support for Chrome >= 81

### PR DESCRIPTION
**Pull request by tinchoz49**
random-access-chrome-file is broken in the latest Chrome (v81).

Related with: https://chromium.googlesource.com/chromium/src/+/5860af49be9d80a85aba59248849495ceff23c77

Every time we write/read from a file we need to have the updated file instance, this PR adds that functionality.

I tested the new version against the benchmark and it performs similar to the old one.

### CODE REVIEW

**Comment by mafintosh** [comment]
@tinchoz49 nice, i don't have time to review this, but can add you here if you wanna maintain this one more easily?

**Comment by tinchoz49** [comment]
oh thanks! that would work

**Comment by mafintosh** [comment]
I think I invited you now

**Comment by mafintosh** [comment]
@tinchoz49 do you have publish rights to npm? can add you there also

**Comment by tinchoz49** [comment]
No, I don't. The would be great too

**Comment by tinchoz49** [comment]
Hi @mafintosh, sorry to bother you, did you give me rights to npm? 

btw: thanks for your help to fix my hyperswarm issues yesterday

**Pull request merged**
